name: Build site

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Install dependencies
        run: |
          sudo apt install -y python3-pip python3-setuptools python3-wheel
          sudo -H pip install nodeenv
          nodeenv --node=22.12.0 node_env
          source node_env/bin/activate
          cd vue-frontend
          npm install
      - name: Check license compatability
        run: |
          source node_env/bin/activate
          cd vue-frontend
          curl -sSfL https://get.anchore.io/syft | sudo sh -s -- -b /usr/local/bin
          syft . -o spdx-json > sbom.spdx.json
          npm ls --omit=dev --depth=0 --json | jq '.dependencies | keys' > deps.json
          jq --slurpfile deps deps.json '
            def clean_license:
              (
                .licenseDeclared,
                .licenseConcluded
              )
              | select(. != null)
              | select(. != "NOASSERTION");

            .packages
            | map(
                select(.name as $n | $deps[0] | index($n))
                | {
                    name,
                    version: .versionInfo,
                    license: (
                      clean_license
                      // (.licenses[]?.license?.id?)
                      // (.licenses[]?.license?)
                      // "UNKNOWN"
                    ),
                    website: (.homepage // .downloadLocation)
                  }
              )
          ' sbom.spdx.json > licenses.json
          cat licenses.json
      - name: Build
        run: |          
          source node_env/bin/activate
          cd vue-frontend
          npm run generate
          rm .output/nitro.json
          tar -czvf .output/public.tar.gz .output/public/
          cp sbom.spdx.json .output
          cp licenses.json .ouput
          cd ..
          ls vue-frontend/.output/
      - name: Archive production artifacts
        uses: actions/upload-artifact@v7
        with:
          name: dist
          archive: false
          path: |
            vue-frontend/.output/public.tar.gz
      - name: Archive production artifacts
        uses: actions/upload-artifact@v7
        with:
          name: dist
          archive: false
          path: |
            vue-frontend/sbom.spdx.json
      - name: Archive production artifacts
        uses: actions/upload-artifact@v7
        with:
          name: dist
          archive: false
          path: |
            vue-frontend/licenses.json
      - name: Upload as a github-pages artifact
        uses: actions/upload-pages-artifact@v5
        with:
          path: vue-frontend/.output/public

  deploy:
    needs: build
    if: github.ref == 'refs/heads/develop'
    permissions:
      pages: write      # to deploy to Pages
      id-token: write   # to verify the deployment originates from an appropriate source
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v5
        # with:
        #   artifact_name: dist
