name: Node.js Build

on:
    push:
    pull_request:

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Set up Node.js
              uses: actions/setup-node@v4
              with:
                    node-version: 'current'
                    check-latest: true
            
            - name: Install dependencies
              run: |
                cd vue-frontend 
                npm install
            - name: Run build
              run: |
                cd vue-frontend
                npm run build

            # - name: Run tests
            #     run: npm test